theme: jekyll-theme-leap-day
title: GEAR Club Website 
author: GEAR Club
email: gavgearclub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
twitter_username: GEARClub5 # DO NOT include the @ character, or else the build will fail!
instagram_username:  gear_club2021 # DO NOT include the @ character, or else the build will fail!
youtube_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
